
### 1. Make a custom exception


In [2]:
class ZeroDivisorError(Exception):
    pass

num = int(input("Enter a divisor: "))

try:
    if num == 0:
        raise ZeroDivisorError("Division by zero is not allowed!")
    print("100 divided by", num, "is", 100 / num)
except ZeroDivisorError as e:
    print("Caught Custom Exception:", e)


Caught Custom Exception: Division by zero is not allowed!


### 2. Make a 2-d array and read and write it in a csv format


In [ ]:
import numpy as np
import csv

with open("Array.csv", "r") as file:
    reader = csv.reader(file)
    loaded_array = np.array([[int(value) for value in row] for row in reader])

print("2D Array read from uploaded CSV file:")
print(loaded_array)


2D Array read from uploaded CSV file:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [  0   1   2   3]]
