In [104]:
import numpy as np
import pandas as pd

### Task 1: Creating Arrays 
1. Write a Python program to:  
- Create a 1D NumPy array of 10 integers ranging from 1 to 10. 
- Create a 2D NumPy array of shape (3, 3) with integers from 1 
to 9. 
- Create a 3D NumPy array with random floating-point numbers 
of shape (3, 5, 3). 
2. Display the shape, size, and datatype of each array. 

In [1]:
import numpy as np

OneD = np.arange(1, 11)
print(OneD, type(OneD), OneD.shape, OneD.size, OneD.dtype)

TwoD = np.random.randint(1, 10, size=(3, 3))
print(TwoD, type(TwoD), TwoD.shape, TwoD.size, TwoD.dtype)

ThreeD = np.random.rand(3, 5, 3)
print(ThreeD, type(ThreeD), ThreeD.shape, ThreeD.size, ThreeD.dtype)


[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'> (10,) 10 int64
[[2 6 1]
 [4 7 4]
 [8 6 8]] <class 'numpy.ndarray'> (3, 3) 9 int32
[[[1.62724402e-01 1.32160221e-01 8.85680180e-01]
  [6.29131580e-01 9.62359995e-01 9.00638808e-01]
  [3.62944130e-01 9.91377256e-01 9.70689149e-01]
  [2.72705930e-01 9.79638349e-01 3.40913577e-01]
  [9.19021076e-01 4.54187325e-01 4.82803165e-01]]

 [[2.66669367e-03 7.45848478e-01 6.01198131e-01]
  [8.66818576e-01 2.69585308e-01 8.17749277e-01]
  [9.07264923e-01 9.92558691e-01 5.34640782e-01]
  [4.51350784e-01 1.31031078e-01 6.59233809e-01]
  [1.98165853e-01 1.17842798e-01 9.51610917e-01]]

 [[1.81140206e-01 6.77293872e-01 2.16026413e-01]
  [3.55708537e-01 9.79631934e-01 4.13383837e-04]
  [7.33148178e-01 1.43401640e-01 2.72874696e-01]
  [7.18807450e-01 5.56482454e-01 2.47304324e-01]
  [8.60948223e-01 4.40134394e-01 3.25028496e-01]]] <class 'numpy.ndarray'> (3, 5, 3) 45 float64


### Task 2: Array Indexing and Slicing 
1. Create a NumPy array from the following list:  
data = [10, 20, 30, 40, 50, 60, 70, 80, 90] 
2. Write a Python program to:  
- Retrieve the first three elements of the array. 
- Retrieve every alternate element of the array. 
- Reverse the array. 
3. Perform the above operations and display the results.

In [3]:
values = [10, 20, 30, 40, 50, 60, 70, 80, 90]
array = np.array(values)
print(array, type(array))

print(array[:3])
print(array[::2])
print(array[::-1])


[10 20 30 40 50 60 70 80 90] <class 'numpy.ndarray'>
[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


### Task 3: Mathematical Operations 
1. Create two NumPy arrays, A and B, each with 5 random integers 
between 1 and 20. 
2. Write a Python program to:  
- Add, subtract, multiply, and divide the two arrays element
wise. 
- Compute the dot product of the arrays. 
- Find the mean, median, standard deviation, and variance of 
array A. 
- Identify the maximum and minimum values in array B and 
their indices.

In [4]:
A = np.random.randint(1, 20, size=(5))
B = np.random.randint(1, 20, size=(5))

Add = A + B
print('Add : ',Add)

subtract = A - B
print('Sub : ',subtract)

mul = A * B
print('Mul : ',mul)

divide = A / B
print('Div : ',divide)

dotPro = np.dot(A, B)
print('Dot ', dotPro)

mean = A.mean()
print('Mean : ',mean)

median = np.median(A)
print('median : ',median)

stdDev = np.std(A)
print(f"SD {stdDev:.2f}")


variance = stdDev ** 2
print(f"Var : {variance:.2f}")



print("Min Element : ", np.min(B))
print("Min Element index: ", np.argmin(B))

print("Max Element : ", np.max(B))
print("Max Element index: ",  np.argmax(B))




Add :  [14 12  6 20 23]
Sub :  [  4   8   0   0 -13]
Mul :  [ 45  20   9 100  90]
Div :  [1.8        5.         1.         1.         0.27777778]
Dot  264
Mean :  7.4
median :  9.0
SD 2.87
Var : 8.24
Min Element :  2
Min Element index:  1
Max Element :  18
Max Element index:  4


### Task 4: Reshaping and Transposing 
1. Create a 1D NumPy array of 12 integers ranging from 1 to 12. 
2. Write a Python program to:  
- Reshape the array into a 2D array of shape (4, 3). 
- Reshape the array into a 3D array of shape (2, 2, 3). 
- Transpose the reshaped 2D array and display its shape.

In [5]:
n1 = np.arange(1, 13)
print(n1, type(n1))
print(n1.reshape(4,3))
print( n1.reshape(2,2,3))
Two_D = n1.reshape(4,3)
transpose2D = Two_D.transpose()
print(transpose2D.shape)


[ 1  2  3  4  5  6  7  8  9 10 11 12] <class 'numpy.ndarray'>
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(3, 4)


### Task 5: Boolean Masking and Filtering 
1. Create a NumPy array with 15 random integers between 10 and 50. 
2. Write a Python program to:  
- Find all elements greater than 25. 
- Replace all elements less than 30 with 0. 
- Count the number of elements divisible by 5. 


In [6]:
a = np.random.randint(10, 50, 15)
print(a)

b = a[a > 25]
print(b)

a[a < 30] = 0
print(a)

c = a[a % 5 == 0]
d = len(c)
print(d)


[46 22 18 17 13 39 48 21 42 16 18 41 49 19 36]
[46 39 48 42 41 49 36]
[46  0  0  0  0 39 48  0 42  0  0 41 49  0 36]
8


### Task 6: Working with Built-in Functions 
#### 1. Use NumPy's built-in functions to:  
- Create an array of 10 equally spaced values between 0 and 1. 
- Create an identity matrix of size 4x4. 
- Generate a 1D array of 20 random integers between 1 and 100, 
sort it, and find the 5 largest elements. 


In [7]:
arr = np.linspace(0,1,10)
print(arr)


print('Identity Matrix')
print(np.eye(4, dtype=int))

OneD = np.random.randint(1, 100, 20)
print("Original Array : ",OneD)

sortArr = np.sort(OneD)
print("Sorted Array : ",sortArr)

print("Largest 5 elements: ",sortArr[-5:])





[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Identity Matrix
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Original Array :  [28 31 87 22 39 16 53 41 28 31 90 34 34 83 64 55 44 63 39 70]
Sorted Array :  [16 22 28 28 31 31 34 34 39 39 41 44 53 55 63 64 70 83 87 90]
Largest 5 elements:  [64 70 83 87 90]




### Task 7: Generic 
#### 1. Create a Python program that:  
- Generates two large random arrays of size (100, 100). 
- Performs matrix multiplication on the two arrays. 
- Finds the determinant and inverse of the resulting matrix (if 
possible). 
- Measures the time taken to complete these operations. 


In [8]:
import numpy as np
import time

start = time.time()

a = np.random.rand(100, 100)
b = np.random.rand(100, 100)

c = np.dot(a, b)
print("mult done")

try:
    d = np.linalg.det(c)
    print("det:", d)

    i = np.linalg.inv(c)
    print("inv done")
except np.linalg.LinAlgError:
    print("inv fail")

end = time.time()
print("time:", round(end - start, 4), "sec")


mult done
det: 8.911400010494252e+49
inv done
time: 0.061 sec
